### ISSUE TITLE
Installation of DataSourceVMWareGuestInfo overwrites used datasources

### ISSUE THREAD

**Issue by sbueringer** [vmware/cloud-init-vmware-guestinfo#24]
The installation script currently sets the datasources via the `99-DataSourceVMwareGuestInfo.cfg`

Therefore cloud-init only trys to detect the VMWareGuetInfo datasource and not all other default datasources. Not sure what the best solution would be:

1. Don't configure the datasource list in the install.sh script (this then would have to been done afterwards by the user)
2. Adjust the list of default datasources instead of configuring the datasource list via the `cloud.cfg.d` folder 
3. Add a file with a lower number to `cloud.cfg.d` which contains all default datasources + `VMwareGuestInfo`

P.S. for more context: https://github.com/kubernetes-sigs/image-builder/issues/96

@akutz what do you think?

**Comment by akutz** [comment]
Hi @sbueringer,

Hmm, the list of datasources can be distro specific, so anything that's non-additive is probably wrong. I wonder if we should remove `99-DataSourceVMwareGuestInfo.cfg` altogether and document that to enable the datasource requires a manual step of adding it to the list of known datasources by creating a file in `/etc/cloud/cloud.cfg.d` or updating the config at `/etc/cloud/cloud.cfg`.

Thoughts?

**Comment by sbueringer** [comment]
Seems good to me. Are there any best practices for datasources which are not delivered directly with cloud-init?

**Comment by akutz** [comment]
This is the only one of which I'm aware. Perhaps it's time for me to get off my butt and get this included in cloud-init.

**Comment by sbueringer** [comment]
That would also be a good solution :)

I'm wondering where cloud-init gets the default list of datasources

**Comment by akutz** [comment]
They have [a default list](https://github.com/canonical/cloud-init/blob/92cc71dec8da73bf43d345418b73db1a32a6b8b9/config/cloud.cfg.tmpl#L36) to which you can append if you submit your own, and there are distro overrides. The cloud-init source is a monorepo, and all datasource/platform specific logic is inside of the repo.

However, they also use a systemd generator to determine the final list. Please see https://github.com/vmware/cloud-init-vmware-guestinfo/commit/9efe9a2f1523e25bbd88e2b8952f0cccf061e0bb and https://github.com/vmware/cloud-init-vmware-guestinfo/commit/d1f6764f6d1adca8117a319bef4cd46acf66c0a7 for more info on this.

**Comment by sbueringer** [comment]
Ah thx. 

So what do you think? Should we just remove the automatic overwrite and document how it can be configured manually?

**Comment by akutz** [comment]
So I *think* if we remove the file and let the systemd generator do its job then it should find the datasource at boot and use it *if* there is data available. I can test this locally with VMware Fusion/Workstation. Please give me some time to test it. 

I added the file because if a single datasource is defined then the generator doesn't bother to figure things out and defers to the single DS. I just wanted to remove any chance the DS wouldn't be used, but it should work without that file.

**Comment by sbueringer** [comment]
Okay perfect. I'll just wait. It's not really an urgent issue for me.

**Comment by akutz** [comment]
FWIW, I'm testing a new image with the addition of the following Ansible task:

```yaml
- name: Remove 99-DataSourceVMwareGuestInfo.cfg
  file:
    path:  /etc/cloud/cloud.cfg.d/99-DataSourceVMwareGuestInfo.cfg
    state: absent
```

If this works then I'll remove the file from **this** repository. Modifying it at the image builder level is just easier for testing.

**Comment by akutz** [comment]
Hi @sbueringer,

So just removing the file doesn't appear to be a good option, because the boot process is testing every datasource provider to see which one(s) should be activated. The boot has taken over three minutes so far. Here's a screenshot:

![image](https://user-images.githubusercontent.com/101085/68689209-9cc84e80-0535-11ea-810f-150e0f0f2fa8.png)

**Comment by akutz** [comment]
In other words, I think for the purposes of the original issue, we should likely add whatever datasources we need to be explicitly part of the list of active datasources. Thoughts?

**Comment by sbueringer** [comment]
I think for this datasource the question is if we want to change the default behaviour of cloud-init. The default behaviour seems to be to check all installed datasoures. Which means it should be best practise anyway to specify which datasources are actually needed. I think now we can decide what it means that somebody installs this datasource. The options could be:
* just the VMWare Guest data source is enabled
* all datasources + VMWare Guest are enabled

I'm not sure if the user usually just wants to use the VMWare Guest datasource when it's installed or if the default use case is that the resulting image is used in different scenarios.

Anyway. It seems the best course of action for every consumer would be to explicitly set the list of datasources to avoid unnecessary delay on boot.

So if we keep the VMWare Guestinfo datasource as-is we would have to either overwrite the `99-DataSourceVMwareGuestInfo.cfg` file or have to create another one with a higher number? Not sure if we can do anything to improve how the datasource list is overwritten (or if there are other options), but it would be okay for me :)

**Comment by donovanmuller** [comment]
Just to add to this, I was setting up a Packer `vsphere-iso` build of Ubuntu 20.04 to be used as a template and after struggling to pass `guestinfo.metadata` successfully from Terraform, I found that Ubuntu [autoinstall](https://ubuntu.com/server/docs/install/autoinstall-quickstart) would create a [`None`](https://cloudinit.readthedocs.io/en/latest/topics/datasources/fallback.html) datasource named `/etc/cloud/cloud.cfg.d/99-installer.cfg` which would take precedence over the `VMwareGuestInfo` datasource referenced in `/etc/cloud/cloud.cfg.d/99-DataSourceVMwareGuestInfo.cfg`.

```console
$ ll /etc/cloud/cloud.cfg.d
total 36
drwxr-xr-x 2 root root 4096 Sep 30 21:25 ./
drwxr-xr-x 4 root root 4096 Sep 30 21:18 ../
-rw-r--r-- 1 root root 2057 Jun  2 15:24 05_logging.cfg
-rw-r--r-- 1 root root  285 Jul 31 16:29 90_dpkg.cfg
-rw-r--r-- 1 root root  549 Sep 30 21:25 99-DataSourceVMwareGuestInfo.cfg
-rw------- 1 root root 1417 Sep 30 21:18 99-installer.cfg
-rw-r--r-- 1 root root  167 Jun  2 15:24 README
-rw-r--r-- 1 root root   35 Sep 30 21:17 curtin-preserve-sources.cfg
-rw-r--r-- 1 root root   28 Sep 30 21:16 subiquity-disable-cloudinit-networking.cfg
```

I renamed `/etc/cloud/cloud.cfg.d/99-installer.cfg` to `/etc/cloud/cloud.cfg.d/99-installer.cfg.old` via Packer provisioner and this resulted in the`VMwareGuestInfo` datasource being identified via `ds-identify`.

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!
