### ISSUE TITLE
Support EL6

### ISSUE THREAD

**Issue by graham1228** [vmware/cloud-init-vmware-guestinfo#38]
EL6 comes  with python 2.6 and from what I can tell python 2.7 is a prereq for this datasource which means EL6 is currently not supported. 

Are their plans to support CentOS/RHEL 6?

**Comment by graham1228** [comment]
Here is some info for my CentOS environment:
```
# cat /etc/centos-release 
CentOS release 6.10 (Final)
# uname -r
2.6.32-754.14.2.el6.x86_64
```
```
# pip show cloud-init | grep -E "Name|Version"
Name: cloud-init
Version: 0.7.9
```
```
# python --version
Python 2.6.6
# pip --version
pip 9.0.3 from /usr/lib/python2.6/site-packages (python 2.6)
```

**2 Issues**

**1. pip is a package and cannot be directly executed**
https://github.com/vmware/cloud-init-vmware-guestinfo/blob/master/install.sh#L78
```
# python -m pip
/usr/bin/python: pip is a package and cannot be directly executed
```
Executing `pip install -r` works without trying to call pip via module

**2. AttributeError: 'module' object has no attribute 'json_dumps'**
https://github.com/vmware/cloud-init-vmware-guestinfo/blob/master/DataSourceVMwareGuestInfo.py#L732
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py", line 736, in <module>
    main()
  File "/usr/lib/python2.6/site-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py", line 732, in main
    print(util.json_dumps(metadata))
AttributeError: 'module' object has no attribute 'json_dumps'
```
json_dumps was introduced via this commit `5a10e5a5022fe8048afc3e5c381636b0d0bc7d75`
Looks like the cloud-init version util module that is supported for EL6 does not have the json_dump function

**Comment by akutz** [comment]
Hi @graham1228,

> Are their plans to support CentOS/RHEL 6?

I created the datasource targeting CentOS 7. In fact, it is the first line of documentation from the DS :)

https://github.com/vmware/cloud-init-vmware-guestinfo/blob/bf996d9e8be63c4fae114a651a5e014f98b7783c/DataSourceVMwareGuestInfo.py#L65

There are no plans at this time to support anything older than CentOS 7.

**Comment by graham1228** [comment]
Given that would you welcome a PR that allows this datasource to install and execute on EL6?

**Comment by skyscooby** [comment]
As far as I can tell json_dumps can be replaced with yaml_dumps on EL6 as this code is only executed when the module is executed directly.. most of the included cloud-init datasources do not even support this mode of execution so you can just drop the main function completely if you want.. I am having some difficulties with the v1 network configuration on EL6 (and EL7) at this time.. looking into it more to see if I can find out what is wrong.

**Comment by skyscooby** [comment]
OK so after further investigation it looks like the 0.7.5 version of cloud init included with EL6 is much older than either Version 1 or Version 2 of the standard network metadata.. 

There is code wired into that version to template out the network configuration but at the time it was required to be in a key called 'network-interfaces' in the ubuntu format.. There is a rhel util converter library that reformatted it into ifcfg-* format.

But the Datasource plugin itself was required to find this key and call the apply_network function itself.
self.distro.apply_network(results['network-interfaces'])

The plugin does work with the user data modules that were supported at that time tho.. so the question really comes even though it 'could' be relatively easy to make this datasource work fully with EL6.. given it's end of life is Nov 2020 does it even make sense at this point?

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!
