### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by excilsploft** [vmware/cloud-init-vmware-guestinfo#5]
This appears not to work with Terraform, I created an OVA with packer (installing the RPM) from the README, importing to a vcenter and marking it as a template.  GOVC appears to use the Govmomi Toolbox and I am not clear that terraform does.  Do I need to edit the OVF manifest, add in the deployment properties, update the sha sum and then push that?  I guess the short version of this question is that does this only work with GOVC as written?

**Comment by akutz** [comment]
Hi @excilsploft,

1. Terraform doesn't really factor into the equation. It's about how you're setting the guest information. That said, it works with Terraform. Please see [this example](https://github.com/vmware/simple-k8s-test-env/tree/master/e2e).
2. OVF has nothing to do with this. This is about the guest info properties, one of which *happens* to be the OVF envelope. 
3. Govc has nothing to do with this.
4. The Toolbox has nothing to do with this.

I simply used `govc` as an example of how to set the guest info properties, but those values could be set any way you deem fit. The only thing needed to make this work on the server is:
1. cloud-init
2. VM Tools
3. This project

**Comment by excilsploft** [comment]
Thanks I just re-read your README this morning and noticed the `extra_config` which seems to be key (without setting up deploy properties in the ovf manifest) I haven't had a chance to test yet but I appreciate your response and the linked example.  I really appreciate this project too because I wrote a similar (albeit differently implemented ) thing last summer when I found the OVF provider in cloud-init did nothing useful

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!
