### ISSUE TITLE
Installation fails on CentOS 7 due to IP address validation error using Python 2.7.5

### ISSUE THREAD

**Issue by marcusportmann** [vmware/cloud-init-vmware-guestinfo#58]
Hello,

Installing the VMware Guest Info provider for cloud-init on CentOS 7 fails as a result of a failure to correctly validate an IP address. The problem is the following line for the **is_valid_ip_addr** method in the **DataSourceVMwareGuestInfo.py** file.

`addr = ipaddress.ip_address(val.encode('utf-8'))`

The value is not being correctly encoded as a unicode string, which is required by the ipaddress module.

I managed to resolve the issue by changing the line to the following:

`addr = ipaddress.ip_address(unicode(val))`

**Comment by akutz** [comment]
I'm confused as to why `val.encode` fails. The [Python docs](https://docs.python.org/2.7/howto/unicode.html) indicate this should work:

> Another important method is .encode([encoding], [errors='strict']), which returns an 8-bit string version of the Unicode string, encoded in the requested encoding. The errors parameter is the same as the parameter of the unicode() constructor, with one additional possibility; as well as ‘strict’, ‘ignore’, and ‘replace’, you can also pass ‘xmlcharrefreplace’ which uses XML’s character references. T

**Comment by akutz** [comment]
Hmm:

```bash
Python 2.7.17 (default, Oct 24 2019, 12:57:47) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ip1 = '1.2.3.4'
>>> str.encode('utf-8')
'hello'
>>> unicode(str)
u'hello'
```

Looks like the `encode('utf-8')` function doesn't actually return a unicode object which is what `ipaddress.ip_address` expects:

1. Define an IP address as a string in Python 2:
    ```bash
    Python 2.7.17 (default, Oct 24 2019, 12:57:47) 
    [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> ip1 = '1.2.3.4'
    ```

2. Import the `ip_address` function:
    ```bash
    >>> from ipaddress import ip_address
    ```

3. Try using the `ip_address` function directly on the variable `ip1`:

    ```bash
    >>> ip_address(ip1)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/akutz/Library/Python/3.7/lib/python/site-packages/ipaddress.py", line 165, in ip_address
        ' a unicode object?' % address)
    ipaddress.AddressValueError: '1.2.3.4' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
    ```

4. Use the `ip_address` function on `ip1` after invoking `unicode` on it:
    ```bash
    >>> ip_address(unicode(ip1))
    IPv4Address(u'1.2.3.4')
    ```

5. Use the `ip_address` function on `ip1` after encoding it with `utf-8`:
    ```bash
    >>> ip_address(ip1.encode('utf-8'))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/akutz/Library/Python/3.7/lib/python/site-packages/ipaddress.py", line 165, in ip_address
        ' a unicode object?' % address)
    ipaddress.AddressValueError: '1.2.3.4' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
    ```
    
Only the `unicode` function worked.

And the following works with Python 3, which is consistent with the patch in #59:

```bash
$ python3
Python 3.7.3 (default, Nov 15 2019, 04:04:52) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ip1 = '1.2.3.4'
>>> from ipaddress import ip_address
>>> ip_address(ip1)
IPv4Address('1.2.3.4')
```

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!
