### ISSUE TITLE
How change hostname in CentOS/RedHat in VmWare vcloud?

### ISSUE THREAD

**Issue by patsevanton** [vmware/cloud-init-vmware-guestinfo#63]
Hello! Thanks cloud-init-vmware-guestinfo!

How change hostname in CentOS/RedHat in VmWare vcloud?

Terraform code:

Terraform 

```
resource "vcd_vapp_vm" "apatsev-env" {
  vapp_name     = vcd_vapp.apatsev.name
  name          = "rhel-78"
  catalog_name  = "xxxxxxxxx"
  template_name = "rhel-78"
  memory        = 8192
  cpus          = 4
  cpu_cores     = 2

  network {
    type               = "org"
    name               = vcd_vapp_org_network.vapp-network.org_network_name
    ip                 = "192.168.22.2"
    ip_allocation_mode = "MANUAL"

  }

  guest_properties = {
      "guestinfo.hostname" = "apatsev-test-vm"
  }

  customization {
    enabled                    = true
    allow_local_admin_password = true
    admin_password             = "xxxxxxxx"
    auto_generate_password     = false
    initscript = <<-EOT
    systemctl disable firewalld
    systemctl stop firewalld
    setenforce 0
    EOT
  }

  depends_on = [vcd_vapp.apatsev]

}
```

```
yum install cloud-init
Failed to set locale, defaulting to C
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Package cloud-init-19.4-7.el7.centos.2.x86_64 already installed and latest version
Nothing to do
```

I installed cloud-init-vmware-guestinfo inside template_name.
But i not installed cloud-init  inside template_name.
Hostname not changed.

Log
https://gist.github.com/patsevanton/226ec818beb76e6e89e56f2a4395a512

**Comment by patsevanton** [comment]
```
 cat /etc/cloud/cloud.cfg.d/99-DataSourceVMwareGuestInfo.cfg
# Cloud-Init Datasource for VMware Guestinfo
#
# Copyright (c) 2018 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Apache 2.0 license (the "License").
# You may not use this product except in compliance with the Apache 2.0 License.
#
# This product may include a number of subcomponents with separate copyright
# notices and license terms. Your use of these subcomponents is subject to the
# terms and conditions of the subcomponent's license, as noted in the LICENSE
# file.

datasource_list: [ "VMwareGuestInfo" ]
```

```
vmware-rpctool "info-get guestinfo.userdata"
No value found
```

```
vmware-rpctool "info-get guestinfo.metadata"
No value found
```


```
/usr/bin/vmtoolsd --cmd 'info-get guestinfo'
Invalid key name supplied
```

```
/usr/bin/vmtoolsd --cmd 'info-get guestinfo.vendordata'
No value found

Debug on article https://vmware.github.io/photon/assets/files/html/3.0/photon_troubleshoot/Troubleshooting-vmtoolsd.html

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!
