### ISSUE TITLE
can somebody build a RPM based on the latest release?

### ISSUE THREAD

**Issue by luoymu** [vmware/cloud-init-vmware-guestinfo#66]
People reported the 1.1.0 RPM does not work correctly and we don't have a RPM for v1.4.2 yet

Thanks

**Comment by varesa** [comment]
It is not trivial to build an RPM of the newer version as it depends on libraries that have not been packaged -> you get an RPM that is missing pieces and doesn't run.

What OS are you trying to use the 1.1.0 RPM on? It should work fine on *el7, but it won't work on *el8 as it targets a different python version

**Comment by fafarun** [comment]
Download the source
dezip the folde on a VM Linux Centos or redhat.. 
in the folder do "make"
the makefile do to generate the rpm file in the new folder rpmbuild/el7/RPMS/noarch/cloud-init-vmware-guestinfo-1.4.1-1.el7.noarch.rpm

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!
