### ISSUE TITLE
keep getting No value for guestinfo

### ISSUE THREAD

**Issue by redridinghood314** [vmware/cloud-init-vmware-guestinfo#67]
hello, 

i'm trying to get ovf customization working on a RHEL 8.2 VM : 
standard deployment (using template) customiztion using cloud-init is working.

but when i try to get this working through OVF deployment, it is not working, OVF properties are set : 
- guestinfo.userdata and guestinfo.userdata.encoding.

which is confirmed by doing : 
vmwre-rpctool 'info get guestinfo.ovfEnv' 

i see in property section : 
<Property oe:key="guestinfo.userdata" oe:value="somebase64value" />
<Property oe:key="guestinfo.userdata.encoding" oe:value="base64" />

but when i try : 
vware-rpctool 'info get guestinfo.userdata' (or guestinfo.userdata.encoding) i always get No Value Found.

so no customization....

i don't understand why , could you help me ?
thanks

regards

**Comment by redridinghood314** [comment]
ok some news, i have tried without specifying guestinfo prefix, same problem. 
so i try another approach : 
i have added extra info in VMX file directly, and it is working.
it seems vApp properties are not managed, which is what i need, do you know why ?

**Comment by almdudler777** [comment]
Hi,

i'm not entirely sure i understand what you're trying to do. I evaluated the ovf approach for my use-case but the charme of the vmwareguestinfo datasource lies in the fact that i can publish the configuration through methods like PowerCLI, REST API or PyVmomi...

As far as i understand the OVF approach one would always need to create a new ovf file with updated cloud-init data for every individual virtual machine?!

I think what you might be looking for is the OVF Datasource for Cloud-init?! https://cloudinit.readthedocs.io/en/latest/topics/datasources/ovf.html https://cloudinit.readthedocs.io/en/latest/topics/datasources/ovf.html

Though that Datasource has nothing to do with this project und should already be included in recent versions of cloud-init...

Greetings,
almi

**Comment by redridinghood314** [comment]
hello thanks for your reply, perhaps i have to change my approach, but i'm not sure to fully understand how you publish your confguration to vm using powercli, could you explain me (or a link that explain me)  ? that would be great.
my main objective is to deploy a custom built OVA and to provide basic configuration during deployment (like ip, credentials....)
thanks for your help

**Comment by almdudler777** [comment]
Hi,

in my setup i'm using what we call internally "Golden Image", which is basically a bare OS-Installation with some tools specific to our environment. Once this golden image is setup the way i want it to, it gets shutdown and just stays that way (one could obviously further turn it into a vm template if one wanted to....)

Now when i need a new vm for a customer, i just use an ansible playbook to clone this golden image vm to a machine under a new name (still powered off). I then use a python script to publish the meta-data and user-data (cloud init) to the newly created vms machine info. Then i power on the machine and cloud-init will take it from there....

For the publishing part: 
For python look at this pyvmomi sample: 
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_vm_extra_config_tags.py 
... on line 46 where it starts with option_values in that python dictionary you could put your customization data...
```python
options_values = {
    "guestinfo.metadata": "<base64+gzip encoded data>",
    "guestinfo.metadata.encoding": "gzip+base64".
    "guestinfo.userdata": "<base64+gzip encoded data>",
    "guestinfo.userdata.encoding": "gzip+base64".
}
```

You could also use the govmomi package as mentioned in the README.md (govc command is part of govmomi)
```
govc vm.change -vm "${VM}" \
  -e guestinfo.metadata="${METADATA}" \
  -e guestinfo.metadata.encoding="gzip+base64" \
  -e guestinfo.userdata="${USERDATA}" \
  -e guestinfo.userdata.encoding="gzip+base64"
```

This article might help if you want to publish extraconfig through PowerCLI:
https://ict-freak.nl/2009/07/08/powercli-add-multiple-values-to-a-vmx-file/


If you want to stick with the OVA Approach LucD has a nice Series about that:
https://www.lucd.info/2019/12/06/cloud-init-part-1-the-basics/



After reading a little bit further Andrew @akutz  might be working on just the solution to your specific problem. Currently this Datasource does not pull in information from ovfEnv at all. This would be changed by this Pull Request:
https://github.com/vmware/cloud-init-vmware-guestinfo/pull/57

So if you wanted to try your solution as it is right now, i would suggest using the DataSourceVMwareGuestInfo.py file from Andrews Pull Request.
https://github.com/vmware/cloud-init-vmware-guestinfo/blob/72c7fce26074818f00c5f49c6ee471d3f5ea0cbf/DataSourceVMwareGuestInfo.py

Hope it helps!

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!
